# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  - member: scooley
    role: Maintain
  - member: yzunger
    role: Maintain
  - member: ncoles
    role: Maintain
  - team: clarity-agent
    role: Maintain